"""
Agent 5 — PR Agent

Fixes applied
─────────────
Bug 3 (broken) — SSE accumulation: returns only new_events; reducer merges.
"""

from datetime import datetime, timezone

from state import ParallaxState
from tools.github_tools import create_pr


def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def pr_agent_node(state: ParallaxState) -> dict:
    new_events: list[dict] = []
    new_events.append({
        "event":     "agent_start",
        "agent":     "pr_agent",
        "timestamp": _now(),
        "data":      {},
    })

    trigger       = state.get("trigger", "")
    pr_url:    str | None = None
    pr_number: int | None = None
    pr_branch: str | None = None
    pr_error:  str | None = None

    if "github.com" in trigger:
        try:
            scan_id        = state.get("scan_id", "unknown")
            repo_url       = trigger.split("@")[0] if "@" in trigger else trigger
            target_branch  = state.get("target_branch", "main")
            pr_branch      = f"parallax/security-fixes-{scan_id[:8]}"
            fixed_findings = state.get("fixed_findings", []) or []

            report_body = (
                "## Parallax Security Audit\n\n"
                f"**Scan ID:** {scan_id}\n\n"
                "Fixes generated by the Parallax dual-model pipeline "
                "(AMD Instinct MI300X · Qwen2.5-Coder-32B).\n"
            )

            pr_url    = create_pr(repo_url, pr_branch,
                                  f"[Parallax] Security fixes for {scan_id[:8]}",
                                  report_body, fixed_findings)
            pr_number = int(pr_url.split("/")[-1]) if pr_url else None
        except Exception as exc:
            pr_error = str(exc)

    new_events.append({
        "event":     "agent_complete",
        "agent":     "pr_agent",
        "timestamp": _now(),
        "data": {
            "pr_url": pr_url,
        },
    })

    return {
        "pr_url":    pr_url,
        "pr_number": pr_number,
        "pr_branch": pr_branch,
        "pr_error":  pr_error,
        "sse_events": new_events,
    }
